name: Daily Standings Update

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install pak
        run: |
          install.packages("pak")
        shell: Rscript {0}

      - name: Install pkgs
        run: |
          pak::pkg_install(c("tidyverse","rvest"), dependencies = TRUE)
        shell: Rscript {0}
        
      - name: Run R script
        run: Rscript scripts/scrape_schedule.R

      - name: Commit and push updated RDS files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add app/data/standings_complete.rds app/data/schedule.rds
          git commit -m "Update standings and schedule [auto]" || echo "No changes to commit"
          git push
