name: Daily Standings Update

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::googledrive
            any::googlesheets4
            any::httr
            any::ragg
            any::tidyverse 
            any::rvest
            any::tidyr
        
      - name: update schedule
        run: Rscript ./scripts/scrape_schedule.R
      
      - name: update win_prob
        run: Rscript ./scripts/exact_win_prob.R
      
      - name: Commit and push updated RDS files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add app/data/standings_complete.rds app/data/schedule.rds app/data/tournament_probabilities.rds
          git commit -m "Update standings, schedule and probabilities [auto]" || echo "No changes to commit"
          git push
